language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-zapp' ]; then cd .. && eval "mv $currentfolder generator-zapp" && cd generator-zapp; fi

